name: EuroSAFs
channels:
  - conda-forge
  - defaults
  - gurobi
dependencies:
  - python=3.7
  - pandas=1.2.1
  - geopandas
  - jupyterlab
  - matplotlib
  - descartes
  - aiohttp
  - fastparquet
  - gurobi
  - xarray
  - xlrd
  - openpyxl
  - scipy
  - netcdf4
  - dask
  - rasterio
  - certifi
  - statsmodels
  - gitpython
